---
- name: configure kibana_yml
  ansible.builtin.template:
    src: "{{ kibana_yml.src }}"
    dest: "/etc/kibana/{{ kibana_yml.file }}"
    owner: root
    group: kibana
    mode: 0660
    backup: "{{ kibana_yml.backup }}"
  notify: restart kibana
  when: kibana_yml.enabled